In [2]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])

In [3]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [23]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
a.reshape(4,3,2,order='A')

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [13]:
a = np.transpose(a,(1,0,2))
a

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [20]:
a.shape

(3, 2, 4)

In [21]:
a = np.reshape(a,(3,4,2))
a = np.transpose(a,(1,0,2))

In [22]:
a

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[12, 13],
        [16, 17],
        [20, 21]],

       [[14, 15],
        [18, 19],
        [22, 23]]])

In [40]:
a = np.arange(4)

In [44]:

a = np.broadcast_to(a,(5,4))

In [42]:
np.transpose(a)

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])